### ISSUE TITLE
add readme examples for get-all-pages?

### ISSUE THREAD

**Issue by metasoarous** [eamonnsullivan/github-api-lib#13]
Hi @eamonnsullivan.

Thanks for putting this library together!

Do you have any usage examples you could put in the readme for `get-all-pages`? It's not clear to me from the docstring how it's supposed to be used.

Thanks again!

**Comment by metasoarous** [comment]
Update: I can see now how this is used in a couple places in other implementations, but it might still be nice to have some higher level description of how to use it: https://github.com/eamonnsullivan/github-api-lib/blob/ffdd029afd88bb3ec266db4e554d9f6e15a8e681/src/eamonnsullivan/github_api_lib/repos.clj#L70-L81

Thanks again!

**Comment by eamonnsullivan** [comment]
Thanks for the note. I'll try to do that later today, or over the weekend. The function depends heavily on the [iteration](https://github.com/eamonnsullivan/github-api-lib/blob/main/src/eamonnsullivan/github_api_lib/core.clj#L42) function, which was suggested to me by its inventor and is destined (last I heard) to be in Clojure 1.11. I suspect there are better examples for that. I'll try to find some.

**Comment by metasoarous** [comment]
Great! Thank you!
